[Rainmeter]
LocalFont="#@#Fonts\ITCAvantGardePro-Bold.ttf"
LocalFont1="#@#Fonts\ITCAvantGardePro-XLt.ttf"
LocalFont2="#@#Fonts\Silkscreen.ttf"
LocalFont3="#@#Fonts\Sansation_Light.ttf"
LocalFont4="#@#Fonts\Sansation_Regular.ttf"
LocalFont5="#@#Fonts\pf_ronda_seven.ttf"

[Variables]
CPU_CORE_GRAPH_LineColor=140,252,124,255
#FONTFACE=Segoe UI
LocalFontFace=ITC Avant Garde Pro Md
LocalFontFace1=ITC Avant Garde Pro XLt
LocalFontFace2=silkscreen
LocalFontFace3=Sansation Light
LocalFontFace4=Sansation
LocalFontFace5=PF Ronda Seven

[Styles]

[StyleTitle]
StringAlign=Center
StringEffect=None
StringStyle=Bold
FontColor=FFFFFF
FontFace=#LocalFontFace4#
FontSize=19
AntiAlias=1

[Standard]
#StringAlign=Center
StringEffect=None
StringStyle=Bold
FontColor=FFFFFF
FontFace=#LocalFontFace3#
FontSize=11
AntiAlias=1

[Small]
#StringAlign=Center
StringEffect=None
StringStyle=Normal
FontColor=FFFFFF
FontFace=#LocalFontFace5#
FontSize=6
AntiAlias=0

[Clock1]
#StringAlign=Center
StringEffect=None
StringStyle=Bold
FontColor=FFFFFF
FontFace=#LocalFontFace4#
FontSize=42
AntiAlias=1

[Clock2]
#StringAlign=Center
StringEffect=None
StringStyle=Bold
FontColor=FFFFFF
FontFace=#LocalFontFace4#
FontSize=18
AntiAlias=1

